### ISSUE TITLE
Metric has non float value

### ISSUE THREAD

**Issue by YohanesHK** [ajclark/datadog-smartmon#5]
Hi Allan,

Thanks for this project, i got some issue when execute "sudo -u dd-agent -- datadog-agent check smartmon" :

Collector
=========

  Running Checks
  ==============
    `
    smartmon (unversioned)
    ----------------------
      Instance ID: smartmon:d884b5186b651429 [WARNING]
      Total Runs: 1
      Metric Samples: Last Run: 13, Total: 13
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 697ms
   
      Warning: Metric: &#39;smartmon.Reallocated_Sector_Ct&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Power_On_Hours&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Reallocated_Sector_Ct&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Power_On_Hours&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Reallocated_Sector_Ct&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Power_On_Hours&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Reallocated_Sector_Ct&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Power_On_Hours&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Reallocated_Sector_Ct&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        
      Warning: Metric: &#39;smartmon.Power_On_Hours&#39; has non float value: &#39;-&#39;. Only float values can be submitted as metrics.
        

Check has run only once, if some metrics are missing you can try again with --check-rate to see any other metric if available.

Can you check it?

Regards,

**Comment by ajclark** [comment]
Hello @YohanesHK 

I cannot reproduce your error. I get: 

`datadog-agent check smartmon --check-rate`

```
    smartmon (unversioned)
    ----------------------
      Instance ID: smartmon:d884b5186b651429 [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/smartmon.yaml
      Total Runs: 2
      Metric Samples: Last Run: 179, Total: 358
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 572ms
      Last Execution Date : 2020-05-30 20:05:26.000000 EDT
      Last Successful Execution Date : 2020-05-30 20:05:26.000000 EDT
```

**Comment by jakelima18** [comment]
I have the same issue.

**Comment by rbernardes** [comment]
This problem come back with new datadog client version.
