### ISSUE TITLE
Minor readme update

### ISSUE THREAD

**Issue by ghost** [ajclark/datadog-smartmon#6]
@ajclark plugin works great. You may just want to update the following so it matches the latest DataDog install paths?

CHANGE FROM:
Copy over the custom check and check config file to the DataDog agent install directory
    cp smartmon.yaml /etc/dd-agent/conf.d/
    cp smartmon.py /etc/dd-agent/checks.d/

CHANGE TO
Copy over the custom check and check config file to the DataDog agent install directory
    cp smartmon.yaml /etc/datadog-agent/conf.d/
    cp smartmon.py /etc/datadog-agent/checks.d/

Just a thought

Hass

**Comment by ajclark** [comment]
Thank you! Fixed!
